### ISSUE TITLE
发送邮件那个脚本，附件中文问题

### ISSUE THREAD

**Issue by lllllllai27** [wbin327/python_util#1]
发送邮件时，如果文件名是中文，显示的名字类似是：`tcmime.3831.4188.4406.bin`这样的命名，请问有什么好的结局办法吗？

**Comment by wbin327** [comment]
网上有许多相关的解决方案，你查一下改一下代码就好了

**Comment by lllllllai27** [comment]
问题解决了，把` email_file["Content-Disposition"] = f'attachment; filename="{file_name}"'`这行代码，改成`email_file.add_header("Content-Disposition", "attachment", filename=file_name)`即可

**Comment by wbin327** [comment]
已修改
